Initial
Max-Pochepets/jv-create-annotation pull request #1
Opened 2021-01-06 22:19 UTC by Max-Pochepets

HW part 1 ready for review. I tried to make the app more versitile.

2021-01-06 22:46 UTC, grom4er requested changes

2021-01-06 22:46 UTC, grom4er commented on src/main/java/core/basesyntax/App.java
> +        Scanner scanner = new Scanner(System.in);
Сканер не должен быть в мейне

2021-01-06 22:46 UTC, grom4er commented on src/main/java/core/basesyntax/App.java
> +}
Вообще в мейне делать логику проверки - очень плохая идея. Мейн не место для проверок.

2021-01-06 22:48 UTC, Max-Pochepets commented on src/main/java/core/basesyntax/App.java
> +        Scanner scanner = new Scanner(System.in);
> Сканер не должен быть в мейне

Это чисто для цикла ввода ставок от новых юзеров

2021-01-06 23:29 UTC, grom4er approved these changes

2021-01-08 10:22 UTC, dmytro-hryhoruk requested changes

2021-01-08 10:22 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +        Dao<User, Bet> dao = new Dao<>(storage);
let's create a different dao for each entity

2021-01-08 10:22 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +                System.out.println("It's Y or N, you silly ^^");
```suggestion
                System.out.println("Enter Y or N, please");
```
It's not really friendly interface

2021-01-08 14:20 UTC, dmytro-hryhoruk requested changes

2021-01-08 14:20 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/App.java
> +        System.out.println("Users:\n" + Storage.usersStorage);
use Dao here

2021-01-08 14:20 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +                || lastName.replaceAll(" ", "").length() == 0) {
String has method isEmpty()

2021-01-08 18:14 UTC, dmytro-hryhoruk approved these changes

2021-01-11 10:40 UTC, merged